# Generated by Django 4.2.5 on 2024-03-14 18:25

from django.db import migrations
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.utils.LowercaseEmailField(max_length=254, unique=True),
        ),
    ]
